const LIST_PAGE_SIZE_OPTIONS_SMALL = [10, 20, 50];
const LIST_PAGE_SIZE_OPTIONS_LARGE = [20, 40, 80];
const ITEM_MASTER_LIMITATION = 100;
const TEXT_LIMITATION = 8;
const TEXT_DEFAULT = 'DEFAULT';
const DATA_TYPES = ['CSV', 'JSON'];
export { DATA_TYPES, LIST_PAGE_SIZE_OPTIONS_SMALL, LIST_PAGE_SIZE_OPTIONS_LARGE, ITEM_MASTER_LIMITATION, TEXT_LIMITATION, TEXT_DEFAULT }