
enum STATUS_DEVICE {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE'
}

enum YES_NO {
    YES = 'YES',
    NO = 'NO'
}
enum LOCATION {
    _2060 = '2060',
    _2048 = '2048'
}
enum MODULES {
    PRINTING_HISTORY = 'PRINTING_HISTORY'
}
enum DRAWER_MENU {
    WIDTH = 340
}
enum ID_MENU {
    PERMISSIONMANAGEMENT = 'PERMISSIONMANAGEMENT',
    DASHBOARD = 'DASHBOARD',
    LOGIN = 'LOGIN',
    ABOUT = 'ABOUT',
    APITOKEN = 'APITOKEN',
    ADMINISTRATION = 'ADMINISTRATION',
    DOZUKI = 'DOZUKI',
    ERROR_PAGE = "ERROR_PAGE",
    NOT_FOUND = 'NOT_FOUND'
}
enum CUSTOMER {
    ARISTA = 'ARISTA',
    CLOUDIAN = 'CLOUDIAN',
    FORTINET = 'FORTINET',
    PELCO = 'PELCO',
    CYLERA = 'CYLERA',
    VERASONICS = 'VERASONICS',
    PERCH = 'PERCH',
    STELLARCYBER = 'STELLARCYBER',
    SILVERPEAK = 'SILVERPEAK',
    QSC = 'QSC',
    ADVANTEST = 'ADVANTEST'
}
enum LABEL_TYPE {
    STANDARD = 'STANDARD',
    FRU = 'FRU'
}
export { STATUS_DEVICE, YES_NO, LOCATION, MODULES, CUSTOMER, LABEL_TYPE, ID_MENU, DRAWER_MENU };